-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 15:52:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Compra_feita_por_paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compra_feita_por_paciente` ;

CREATE TABLE IF NOT EXISTS `Compra_feita_por_paciente` (
  `idCompra_paciente` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT ZEROFILL NOT NULL,
  `data` DATE NOT NULL,
  `idLote` INT NOT NULL,
  PRIMARY KEY (`idCompra_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compra_para_clínica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compra_para_clínica` ;

CREATE TABLE IF NOT EXISTS `Compra_para_clínica` (
  `idCompra_médico` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT ZEROFILL NOT NULL,
  `data` DATE NOT NULL,
  `médico` VARCHAR(45) NOT NULL,
  `id_Lote` INT NOT NULL,
  PRIMARY KEY (`idCompra_médico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lote` ;

CREATE TABLE IF NOT EXISTS `Lote` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `idRemédio` INT NOT NULL,
  `idCompra_Médico` INT NOT NULL,
  `quantidade` INT ZEROFILL NOT NULL,
  `data_validade` DATE NOT NULL,
  `Compra_para_clínica_idCompra_médico` INT NOT NULL,
  `Compra_feita_por_paciente_idCompra_paciente` INT NOT NULL,
  PRIMARY KEY (`idLote`, `Compra_para_clínica_idCompra_médico`, `Compra_feita_por_paciente_idCompra_paciente`),
  CONSTRAINT `fk_Lote_Compra_para_clínica1`
    FOREIGN KEY (`Compra_para_clínica_idCompra_médico`)
    REFERENCES `Compra_para_clínica` (`idCompra_médico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lote_Compra_feita_por_paciente1`
    FOREIGN KEY (`Compra_feita_por_paciente_idCompra_paciente`)
    REFERENCES `Compra_feita_por_paciente` (`idCompra_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Lote_Compra_para_clínica1_idx` ON `Lote` (`Compra_para_clínica_idCompra_médico` ASC) VISIBLE;

CREATE INDEX `fk_Lote_Compra_feita_por_paciente1_idx` ON `Lote` (`Compra_feita_por_paciente_idCompra_paciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Médico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Médico` ;

CREATE TABLE IF NOT EXISTS `Médico` (
  `crm` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobre_nome` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(90) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `Compra_médico_id_Compra_médico` INT NOT NULL,
  `Compra_paciente_idCompra_paciente` INT NOT NULL,
  PRIMARY KEY (`crm`, `Compra_médico_id_Compra_médico`, `Compra_paciente_idCompra_paciente`),
  CONSTRAINT `fk_Médico_Compra_médico1`
    FOREIGN KEY (`Compra_médico_id_Compra_médico`)
    REFERENCES `Compra_para_clínica` (`idCompra_médico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Médico_Compra_paciente1`
    FOREIGN KEY (`Compra_paciente_idCompra_paciente`)
    REFERENCES `Compra_feita_por_paciente` (`idCompra_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `crm_UNIQUE` ON `Médico` (`crm` ASC) VISIBLE;

CREATE INDEX `fk_Médico_Compra_médico1_idx` ON `Médico` (`Compra_médico_id_Compra_médico` ASC) VISIBLE;

CREATE INDEX `fk_Médico_Compra_paciente1_idx` ON `Médico` (`Compra_paciente_idCompra_paciente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Remédio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Remédio` ;

CREATE TABLE IF NOT EXISTS `Remédio` (
  `idRemédio` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) ZEROFILL NOT NULL,
  `estoque` INT ZEROFILL NOT NULL,
  `Lote_id_Lote` INT NOT NULL,
  `Lote_idLote` INT NOT NULL,
  PRIMARY KEY (`idRemédio`, `Lote_id_Lote`, `Lote_idLote`),
  CONSTRAINT `fk_Remédio_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nome_UNIQUE` ON `Remédio` (`nome` ASC) VISIBLE;

CREATE INDEX `fk_Remédio_Lote1_idx` ON `Remédio` (`Lote_idLote` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
